version: "3"

services:
      
  webapp:
    build: .
    restart: always
    ports:
      - 8070:8080
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    networks:
      - net-backend
    depends_on:
      - db-spring

  db-spring:
    image: mysql:5.7
    container_name: db-spring
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - net-backend

networks:
  net-backend: